DOCUMENT		= $(SRC_DIR)main
SRC_DIR			= ./src/
COMPILER		= pdflatex
BIBER			= biber
BUILD_FILES		= *.{pdf,log,aux,bcf,out,run,xml,toc}
BIB_FILES		= *.{bbl,blg}

all: help

help:
	@echo "These are all the options available:"
	@echo -e "build\t\t- compile the .tex files to generate the pdf"
	@echo -e "clean\t\t- remove all the files generated by the 'build' option."
	@echo -e "help\t\t- show this message."

build: clean
	$(COMPILER)	$(DOCUMENT).tex
	$(BIBER)	$(DOCUMENT)
	$(COMPILER)	$(DOCUMENT).tex
	$(COMPILER)	$(DOCUMENT).tex

clean:
	rm -rf $(SRC_DIR)$(BUILD_FILES)
	rm -rf $(SRC_DIR)$(BIB_FILES)
