all: help

help:
	@echo "These are all the options available:"
	@echo -e "build\t\t- compile the .tex files to generate the pdf"
	@echo -e "clean\t\t- remove all the files generated by the 'build' option."
	@echo -e "help\t\t- show this message."

build: clean
	pdflatex main.tex
	biber main
	pdflatex main.tex

clean:
	rm -rf main.aux main.log main.out main.toc main.pdf
	rm -rf main.bbl main.bcf main.blg main.run.xml
